# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160511_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedstory',
            name='destination',
            field=models.CharField(blank=True, help_text='The trip destination', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curatedstory',
            name='terminal',
            field=models.CharField(blank=True, choices=[(b'T1', b'Terminal 1'), (b'T2', b'Terminal 2'), (b'T3', b'Terminal 3'), (b'T4', b'Terminal 4'), (b'T5', b'Terminal 5')], help_text='The Heathrow terminal number flown from/into', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='featuredstory',
            name='destination',
            field=models.CharField(blank=True, help_text='The trip destination', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='featuredstory',
            name='terminal',
            field=models.CharField(blank=True, choices=[(b'T1', b'Terminal 1'), (b'T2', b'Terminal 2'), (b'T3', b'Terminal 3'), (b'T4', b'Terminal 4'), (b'T5', b'Terminal 5')], help_text='The Heathrow terminal number flown from/into', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='destination',
            field=models.CharField(blank=True, help_text='The trip destination', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='terminal',
            field=models.CharField(blank=True, choices=[(b'T1', b'Terminal 1'), (b'T2', b'Terminal 2'), (b'T3', b'Terminal 3'), (b'T4', b'Terminal 4'), (b'T5', b'Terminal 5')], help_text='The Heathrow terminal number flown from/into', max_length=2, null=True),
        ),
    ]
