# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160516_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='agree_marketting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='uk_resident',
            field=models.BooleanField(default=False),
        ),
    ]
