# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_featuredstory_person_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ('importance',)},
        ),
    ]
