# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160523_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedstory',
            name='dummy_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuredstory',
            name='dummy_content',
            field=models.BooleanField(default=False),
        ),
    ]
