# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160523_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredstory',
            name='person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
