# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160602_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('importance', models.IntegerField(default=50)),
                ('embargo_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('ready_to_publish', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
        ),
    ]
