# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_plaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaque',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
