# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plaque_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaque',
            name='pin_number',
            field=models.IntegerField(null=True),
        ),
    ]
