# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 14:29
from __future__ import unicode_literals

from django.db import migrations


def get_pin_number(apps, schema_editor):
    Plaque = apps.get_model('core', 'Plaque')
    for plaque in Plaque.objects.all():
        plaque.pin_number = plaque.pk
        plaque.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_plaque_pin_number'),
    ]

    operations = [
    	migrations.RunPython(get_pin_number)
    ]
