# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Student', 'Student')], max_length=1),
        ),
    ]
