# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160827_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Student', 'Student')], default=b'Student', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
