# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160830_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='availability_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='availability_to',
            field=models.DateTimeField(),
        ),
    ]
