# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160830_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='availability_from',
            field=models.DateTimeField(verbose_name='Available From'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='availability_to',
            field=models.DateTimeField(verbose_name='Available To'),
        ),
    ]
