# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160830_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='availability_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available From'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='availability_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available To'),
        ),
    ]
