# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160830_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='avatar',
            field=models.URLField(default=b'http://simpleicon.com/wp-content/uploads/user-2.png', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.FilePathField(choices=[('Tutor', 'Tutor'), ('Student', 'Student')], default=b'Student', max_length=10),
        ),
    ]
