# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160904_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='subjects',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='subjects',
            field=models.CharField(blank=True, max_length=30, verbose_name='subjects'),
        ),
    ]
