# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0014_auto_20160906_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='subjects',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.Subjects'),
        ),
    ]
